package com.dataentry.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Filter;

import java.time.Instant;

/**
 * Bookkeeping row for one in-flight chunked upload. The bytes themselves live on disk under
 * {@code app.uploads.incoming-dir/<id>/payload.bin}; which chunks have landed is tracked by
 * marker files next to it, so parallel chunk writes never contend on this row.
 *
 * <p>Rows are short-lived: a session is deleted the moment it is completed or aborted, and
 * a scheduled sweep removes anything that outlived {@code expiresAt}.
 */
@Entity
@Table(
        name = "upload_sessions",
        indexes = {
                @Index(name = "ix_upload_sessions_owner", columnList = "owner_id"),
                @Index(name = "ix_upload_sessions_expires", columnList = "expires_at")
        }
)
@Filter(name = "teamFilter", condition = "team_id = :teamId")
@EntityListeners(TenantEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class UploadSession implements TeamOwned {

    /** Random UUID, generated by the service. Doubles as the on-disk directory name. */
    @Id
    @Column(length = 36)
    private String id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "team_id")
    private Team team;

    /** The user who opened the session — the only one allowed to feed or finish it. */
    @Column(name = "owner_id", nullable = false)
    private Long ownerId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 32)
    private UploadTarget target;

    @Column(name = "project_id")
    private Long projectId;

    @Column(name = "department_id")
    private Long departmentId;

    @Column(name = "ticket_id")
    private Long ticketId;

    /** Ticket title (quick upload) or document display name (ticket attachment). */
    @Column(length = 250)
    private String title;

    @Column(name = "original_filename", nullable = false, length = 300)
    private String originalFilename;

    /** MIME the browser claimed. Informational only — the real type is sniffed on finalize. */
    @Column(name = "client_content_type", length = 200)
    private String clientContentType;

    @Column(name = "declared_size", nullable = false)
    private long declaredSize;

    @Column(name = "chunk_bytes", nullable = false)
    private int chunkBytes;

    @Column(name = "total_chunks", nullable = false)
    private int totalChunks;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private Instant createdAt = Instant.now();

    @Column(name = "expires_at", nullable = false)
    private Instant expiresAt;
}
