-- Browser push notifications (Web Push: RFC 8030 delivery, RFC 8188/8291 payload
-- encryption, RFC 8292 VAPID). One row per browser subscription the user opted in
-- from. The endpoint is unique service-wide: a browser issues one endpoint per
-- (origin, service-worker) pair, so no two users can ever collide on it.

CREATE TABLE push_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    endpoint character varying(2048) NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    user_agent character varying(300),
    created_at timestamp(6) with time zone NOT NULL,
    last_success_at timestamp(6) with time zone,
    CONSTRAINT uq_push_subscriptions_endpoint UNIQUE (endpoint)
);

-- "Send to every browser this user opted in from."
CREATE INDEX ix_push_subscriptions_user ON push_subscriptions (user_id);
