-- Feature pack: personal daily goals (B5) and team announcements (C2).
-- The goal is informational only — a progress ring on the agent dashboard, never
-- an enforced quota. Announcements are the admin broadcast record + history.

ALTER TABLE users ADD COLUMN daily_goal integer NOT NULL DEFAULT 50
    CHECK (daily_goal BETWEEN 1 AND 1000);

CREATE TABLE announcements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint REFERENCES teams(id) ON DELETE CASCADE,
    created_by_id bigint REFERENCES users(id) ON DELETE SET NULL,
    title character varying(200) NOT NULL,
    body text NOT NULL,
    -- ALL = everyone in the team, USERS = data-entry agents, ADMINS = team leaders.
    audience character varying(10) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT announcements_audience_check CHECK (audience IN ('ALL', 'USERS', 'ADMINS'))
);

-- Broadcast history, newest first inside the team.
CREATE INDEX ix_announcements_team_created_at
    ON announcements (team_id, created_at DESC);
