-- Group chat: any number of members, with one or more ADMIN members (the creator, and
-- anyone an admin promotes) who can add/remove members, promote/demote, and rename the
-- group. Kept as its own set of tables rather than folded into chat_conversations /
-- chat_messages — group and 1:1 read-tracking are genuinely different shapes (a single
-- read_at per message vs. one last-read watermark per member per group) — so this way
-- neither can break the other, and the existing 1:1 chat is untouched by this migration.

CREATE TABLE chat_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint REFERENCES teams(id) ON DELETE CASCADE,
    name character varying(150) NOT NULL,
    created_by_id bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamp(6) with time zone NOT NULL,
    last_message_at timestamp(6) with time zone
);

CREATE INDEX ix_chat_groups_team ON chat_groups (team_id, last_message_at DESC);

-- role is a plain varchar (not an enum type) so a future third role needs no DDL.
CREATE TABLE chat_group_members (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint NOT NULL REFERENCES chat_groups(id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role character varying(10) NOT NULL DEFAULT 'MEMBER',
    joined_at timestamp(6) with time zone NOT NULL,
    -- Per-member watermark: "messages after this instant are unread for this member" —
    -- one row per (group, member) instead of one row per (message, member), which is
    -- what a durable unread count needs without a combinatorial read-receipts table.
    last_read_at timestamp(6) with time zone,
    CONSTRAINT chat_group_members_uk UNIQUE (group_id, user_id),
    CONSTRAINT chat_group_members_role_check CHECK (role IN ('ADMIN', 'MEMBER'))
);

CREATE INDEX ix_chat_group_members_user ON chat_group_members (user_id);
CREATE INDEX ix_chat_group_members_group ON chat_group_members (group_id);

-- kind distinguishes an ordinary message from a system line ("X added Y", "Z left") so
-- the client can render the second one centered/muted without a body from any sender.
CREATE TABLE chat_group_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint NOT NULL REFERENCES chat_groups(id) ON DELETE CASCADE,
    sender_id bigint REFERENCES users(id) ON DELETE SET NULL,
    body character varying(4000),
    kind character varying(16) NOT NULL DEFAULT 'TEXT',
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT chat_group_messages_kind_check CHECK (kind IN ('TEXT', 'SYSTEM'))
);

CREATE INDEX ix_chat_group_messages_group_created ON chat_group_messages (group_id, created_at);

CREATE TABLE chat_group_attachments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id bigint NOT NULL REFERENCES chat_group_messages(id) ON DELETE CASCADE,
    original_filename character varying(255) NOT NULL,
    stored_name character varying(255) NOT NULL,
    content_type character varying(100),
    size_bytes bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);

CREATE INDEX ix_chat_group_attachments_message ON chat_group_attachments (message_id);
