CREATE TABLE cleaned_files (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL REFERENCES projects(id),
    department_id bigint NOT NULL REFERENCES departments(id),
    title varchar(250) NOT NULL,
    original_filename varchar(250) NOT NULL,
    storage_key varchar(100) NOT NULL UNIQUE,
    size_bytes bigint NOT NULL CHECK (size_bytes > 0),
    sha256 varchar(64) NOT NULL,
    cleaned_on date NOT NULL,
    due_on date,
    source_reference varchar(500),
    notes varchar(4000),
    status varchar(20) NOT NULL CHECK (status IN ('READY', 'IN_PROGRESS', 'COMPLETED')),
    uploaded_by varchar(150) NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    started_at timestamp(6) with time zone,
    completed_at timestamp(6) with time zone,
    version bigint NOT NULL DEFAULT 0,
    CHECK (due_on IS NULL OR due_on >= cleaned_on)
);
CREATE INDEX ix_cleaned_files_project_department ON cleaned_files(project_id, department_id, id DESC);
CREATE INDEX ix_cleaned_files_status_cleaned ON cleaned_files(status, cleaned_on, id DESC);
