CREATE TABLE api_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    created_by_user_id bigint,
    expires_at timestamp(6) with time zone,
    last_used_at timestamp(6) with time zone,
    name character varying(150) NOT NULL,
    prefix character varying(12) NOT NULL,
    revoked_at timestamp(6) with time zone,
    token_hash character varying(64) NOT NULL,
    CONSTRAINT idx_api_tokens_hash UNIQUE (token_hash)
);

CREATE TABLE audit_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action character varying(50) NOT NULL,
    actor_id bigint,
    actor_username character varying(100),
    created_at timestamp(6) with time zone NOT NULL,
    details character varying(2000),
    entity_id bigint,
    entity_type character varying(50) NOT NULL,
    team_id bigint
);

CREATE TABLE teams (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    color character varying(20),
    created_at timestamp(6) with time zone NOT NULL,
    created_by_id bigint,
    description character varying(300),
    name character varying(150) NOT NULL,
    name_ar character varying(150),
    name_en character varying(150),
    slug character varying(60) NOT NULL,
    CONSTRAINT uk_team_slug UNIQUE (slug)
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    avatar_updated_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    display_name character varying(150),
    display_name_ar character varying(150),
    display_name_en character varying(150),
    email character varying(200),
    password_hash character varying(255) NOT NULL,
    phone character varying(40),
    role character varying(20) NOT NULL,
    username character varying(100) NOT NULL,
    team_id bigint,
    CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['SUPER_ADMIN'::character varying, 'ADMIN'::character varying, 'USER'::character varying])::text[])))
);

CREATE TABLE projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    end_date date,
    name character varying(200) NOT NULL,
    name_ar character varying(200),
    name_en character varying(200),
    progress integer NOT NULL,
    start_date date,
    status character varying(20) NOT NULL,
    subtitle character varying(250),
    subtitle_ar character varying(250),
    subtitle_en character varying(250),
    department_id bigint,
    team_id bigint,
    CONSTRAINT projects_status_check CHECK (((status)::text = ANY ((ARRAY['ON_TRACK'::character varying, 'DELAYED'::character varying, 'COMPLETED'::character varying])::text[])))
);

CREATE TABLE departments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(150) NOT NULL,
    name_ar character varying(150),
    name_en character varying(150),
    project_id bigint,
    team_id bigint,
    CONSTRAINT uk_department_team_name UNIQUE (team_id, name)
);

CREATE TABLE subcategories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(150) NOT NULL,
    name_ar character varying(150),
    name_en character varying(150),
    department_id bigint NOT NULL,
    team_id bigint,
    CONSTRAINT uk_subcategory_department_name UNIQUE (department_id, name)
);

CREATE TABLE custom_fields (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    display_order integer NOT NULL,
    field_key character varying(100) NOT NULL,
    label character varying(150) NOT NULL,
    label_ar character varying(150),
    label_en character varying(150),
    options character varying(2000),
    options_ar character varying(2000),
    options_en character varying(2000),
    placeholder character varying(250),
    placeholder_ar character varying(250),
    placeholder_en character varying(250),
    required boolean NOT NULL,
    type character varying(20) NOT NULL,
    subcategory_id bigint,
    team_id bigint,
    CONSTRAINT custom_fields_type_check CHECK (((type)::text = ANY ((ARRAY['TEXT'::character varying, 'TEXTAREA'::character varying, 'NUMBER'::character varying, 'URL'::character varying, 'EMAIL'::character varying, 'DATE'::character varying, 'SELECT'::character varying])::text[])))
);

CREATE TABLE tickets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    content_ar text,
    content_en text,
    status character varying(20) NOT NULL,
    submitted_at timestamp(6) with time zone NOT NULL,
    title character varying(500),
    title_ar character varying(500),
    title_en character varying(500),
    website_link character varying(500),
    website_name character varying(250),
    website_name_ar character varying(250),
    website_name_en character varying(250),
    department_id bigint NOT NULL,
    project_id bigint,
    subcategory_id bigint,
    submitted_by_id bigint NOT NULL,
    team_id bigint,
    CONSTRAINT tickets_status_check CHECK (((status)::text = ANY ((ARRAY['IN_PROGRESS'::character varying, 'REVIEW'::character varying, 'COMPLETED'::character varying])::text[])))
);

CREATE TABLE ticket_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type character varying(200),
    name character varying(250) NOT NULL,
    original_filename character varying(300) NOT NULL,
    size_bytes bigint NOT NULL,
    storage_path character varying(500) NOT NULL,
    uploaded_at timestamp(6) with time zone NOT NULL,
    ticket_id bigint NOT NULL,
    content_hash character varying(64)
);

CREATE TABLE ticket_resources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_order integer NOT NULL,
    name character varying(250),
    name_ar character varying(250),
    name_en character varying(250),
    url character varying(500) NOT NULL,
    ticket_id bigint NOT NULL
);

CREATE TABLE ticket_field_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value text,
    value_ar text,
    value_en text,
    field_id bigint NOT NULL,
    ticket_id bigint NOT NULL,
    CONSTRAINT ukkylyk4l0ypmvfmchjke5c4y1a UNIQUE (ticket_id, field_id)
);

CREATE TABLE project_members (
    project_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT project_members_pkey PRIMARY KEY (project_id, user_id)
);

CREATE TABLE notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL,
    message character varying(500) NOT NULL,
    project_id bigint,
    read_at timestamp(6) with time zone,
    ref_id bigint,
    ref_type character varying(40),
    type character varying(40) NOT NULL,
    recipient_id bigint NOT NULL
);

CREATE TABLE login_attempts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_key character varying(200) NOT NULL,
    attempted_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE user_avatars (
    user_id bigint PRIMARY KEY,
    content_type character varying(80) NOT NULL,
    data bytea NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL
);

CREATE TABLE upload_sessions (
    id character varying(36) PRIMARY KEY,
    team_id bigint,
    owner_id bigint NOT NULL,
    target character varying(32) NOT NULL,
    project_id bigint,
    department_id bigint,
    ticket_id bigint,
    title character varying(250),
    original_filename character varying(300) NOT NULL,
    client_content_type character varying(200),
    declared_size bigint NOT NULL,
    chunk_bytes integer NOT NULL,
    total_chunks integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT upload_sessions_target_check CHECK (((target)::text = ANY ((ARRAY['QUICK_UPLOAD'::character varying, 'TICKET_DOCUMENT'::character varying])::text[])))
);

CREATE TABLE dataset_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_ticket_id bigint NOT NULL,
    team_id bigint,
    team_name character varying(250),
    project_id bigint,
    project_name character varying(500),
    department_id bigint,
    department_name character varying(500),
    subcategory_id bigint,
    subcategory_name character varying(500),
    submitted_by_user_id bigint,
    submitted_by_username character varying(150),
    submitted_by_display_name character varying(250),
    submitted_by_email character varying(320),
    submitted_by_phone character varying(80),
    submitted_by_role character varying(40),
    title character varying(500),
    content text,
    website_name character varying(250),
    website_link character varying(1000),
    status character varying(40),
    submitted_at timestamp(6) with time zone,
    attachments_json text NOT NULL,
    attachment_count integer,
    custom_fields_json text NOT NULL,
    source_fingerprint character varying(64) NOT NULL,
    published_at timestamp(6) with time zone NOT NULL,
    refreshed_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_dataset_records_source_ticket UNIQUE (source_ticket_id)
);


ALTER TABLE ONLY audit_logs
    ADD CONSTRAINT fkn197dpl4m55sqnpdxovoevddt FOREIGN KEY (team_id) REFERENCES teams(id);

ALTER TABLE ONLY users
    ADD CONSTRAINT fkfjws1rdruab2bqg7qipoqf65r FOREIGN KEY (team_id) REFERENCES teams(id);

ALTER TABLE ONLY projects
    ADD CONSTRAINT fkk7yeevqj2y4etn45lq8ilgxdh FOREIGN KEY (department_id) REFERENCES departments(id);

ALTER TABLE ONLY projects
    ADD CONSTRAINT fkmqih0928bq6r3gbuh47giq8w FOREIGN KEY (team_id) REFERENCES teams(id);

ALTER TABLE ONLY departments
    ADD CONSTRAINT fkae8h4nwnqpfcr5078n17b0lgo FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY departments
    ADD CONSTRAINT fkdumdkq71rwk1f8po51tamwrmv FOREIGN KEY (team_id) REFERENCES teams(id);

ALTER TABLE ONLY subcategories
    ADD CONSTRAINT fka5nhtboohcrsxj4f79nipor9d FOREIGN KEY (department_id) REFERENCES departments(id);

ALTER TABLE ONLY subcategories
    ADD CONSTRAINT fkmj6ciuxckvg7bn94cdsi7ueva FOREIGN KEY (team_id) REFERENCES teams(id);

ALTER TABLE ONLY custom_fields
    ADD CONSTRAINT fk1rgn13g7286ius5ird9xx4sjk FOREIGN KEY (subcategory_id) REFERENCES subcategories(id);

ALTER TABLE ONLY custom_fields
    ADD CONSTRAINT fkbdjxgapjstn8tvvxcke0ty9kj FOREIGN KEY (team_id) REFERENCES teams(id);

ALTER TABLE ONLY tickets
    ADD CONSTRAINT fkniytk8tt6hm2phdg1dpcdbb4j FOREIGN KEY (subcategory_id) REFERENCES subcategories(id);

ALTER TABLE ONLY tickets
    ADD CONSTRAINT fknmqlf7bvhd4wmn10w1pmvalpv FOREIGN KEY (team_id) REFERENCES teams(id);

ALTER TABLE ONLY tickets
    ADD CONSTRAINT fknnknc865fpw29hxyq3ma26rqo FOREIGN KEY (department_id) REFERENCES departments(id);

ALTER TABLE ONLY tickets
    ADD CONSTRAINT fkp9858ag8eff6chcg2sbv5fm3x FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY tickets
    ADD CONSTRAINT fkpnpnx163x9arq52kucsfgxjym FOREIGN KEY (submitted_by_id) REFERENCES users(id);

ALTER TABLE ONLY ticket_documents
    ADD CONSTRAINT fkfyeobg7t725e0dqgyht1ghujs FOREIGN KEY (ticket_id) REFERENCES tickets(id);

ALTER TABLE ONLY ticket_resources
    ADD CONSTRAINT fksw1p4e3my8r5p0hfc1im2xv35 FOREIGN KEY (ticket_id) REFERENCES tickets(id);

ALTER TABLE ONLY ticket_field_values
    ADD CONSTRAINT fk3yd0fe5d15mbcbukufa0ulx46 FOREIGN KEY (field_id) REFERENCES custom_fields(id);

ALTER TABLE ONLY ticket_field_values
    ADD CONSTRAINT fkelskrvgioe7a4io6319lvth6e FOREIGN KEY (ticket_id) REFERENCES tickets(id);

ALTER TABLE ONLY project_members
    ADD CONSTRAINT fkdki1sp2homqsdcvqm9yrix31g FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY project_members
    ADD CONSTRAINT fkgul2el0qjk5lsvig3wgajwm77 FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY notifications
    ADD CONSTRAINT fkqqnsjxlwleyjbxlmm213jaj3f FOREIGN KEY (recipient_id) REFERENCES users(id);

ALTER TABLE ONLY upload_sessions
    ADD CONSTRAINT fk_upload_sessions_team FOREIGN KEY (team_id) REFERENCES teams(id);


CREATE INDEX idx_audit_actor ON audit_logs USING btree (actor_id);
CREATE INDEX idx_audit_created_at ON audit_logs USING btree (created_at);
CREATE INDEX idx_audit_entity ON audit_logs USING btree (entity_type, entity_id);
CREATE INDEX idx_audit_team ON audit_logs USING btree (team_id);
CREATE INDEX idx_login_attempts_key_time ON login_attempts USING btree (attempt_key, attempted_at);
CREATE INDEX ix_notifications_recipient_unread ON notifications USING btree (recipient_id, read_at, created_at);

CREATE INDEX ix_upload_sessions_owner ON upload_sessions USING btree (owner_id);
CREATE INDEX ix_upload_sessions_expires ON upload_sessions USING btree (expires_at);
CREATE INDEX idx_dataset_published_at ON dataset_records USING btree (published_at);
