-- Team-leader assigned work items ("assignments"): a leader writes a task for one agent,
-- the agent marks it done, and the leader sees the completion. Distinct from tickets
-- (data-entry records) — an assignment is an instruction, not captured data.

CREATE TABLE assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint REFERENCES teams(id),
    title character varying(200) NOT NULL,
    description text,
    status character varying(20) NOT NULL,
    due_date date,
    assignee_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    assigned_by_id bigint REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamp(6) with time zone NOT NULL,
    completed_at timestamp(6) with time zone,
    CONSTRAINT assignments_status_check CHECK (status IN ('OPEN', 'DONE'))
);

-- Team leader list: newest first inside the team.
CREATE INDEX ix_assignments_team_created_at
    ON assignments (team_id, created_at DESC);

-- Agent "my assignments" view: filter by assignee (+ status), newest first.
CREATE INDEX ix_assignments_assignee_status_created_at
    ON assignments (assignee_id, status, created_at DESC);
