-- Direct (1:1) messaging: any two members (USER / ADMIN / SUPER_ADMIN) can open a
-- conversation, exchange text and attachments (pdf/word/images), and get live delivery
-- through the /ws/chat WebSocket endpoint. Canonical ordering: user_a_id < user_b_id.

CREATE TABLE chat_conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint REFERENCES teams(id),
    user_a_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    user_b_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at timestamp(6) with time zone NOT NULL,
    last_message_at timestamp(6) with time zone,
    CONSTRAINT chat_conversations_pair_uk UNIQUE (user_a_id, user_b_id),
    CONSTRAINT chat_conversations_order_check CHECK (user_a_id < user_b_id)
);

CREATE INDEX ix_chat_conv_a_last ON chat_conversations (user_a_id, last_message_at DESC);
CREATE INDEX ix_chat_conv_b_last ON chat_conversations (user_b_id, last_message_at DESC);

CREATE TABLE chat_messages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id bigint NOT NULL REFERENCES chat_conversations(id) ON DELETE CASCADE,
    sender_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    body character varying(4000),
    created_at timestamp(6) with time zone NOT NULL,
    read_at timestamp(6) with time zone
    -- body may be NULL when the message is attachments-only (pdf/word/image)
);

CREATE INDEX ix_chat_messages_conv_created ON chat_messages (conversation_id, created_at);
CREATE INDEX ix_chat_messages_conv_unread ON chat_messages (conversation_id, sender_id, read_at);

CREATE TABLE chat_attachments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id bigint NOT NULL REFERENCES chat_messages(id) ON DELETE CASCADE,
    original_filename character varying(255) NOT NULL,
    stored_name character varying(255) NOT NULL,
    content_type character varying(100),
    size_bytes bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);

CREATE INDEX ix_chat_attachments_message ON chat_attachments (message_id);
