#!/usr/bin/env bash
#
# Generates the .env file that docker-compose.yml requires, next to the compose file.
#
# .env is deliberately gitignored — it holds the database password, the JWT signing key
# and the seed admin passwords, none of which belong in the repository. This script is
# the supported way to produce it on a server after a fresh clone or pull:
#
#   ./scripts/setup-env.sh                 # prompts for the database password
#   DB_PASSWORD=secret ./scripts/setup-env.sh   # non-interactive (CI / provisioning)
#   ./scripts/setup-env.sh --force         # overwrite an existing .env
#
# Everything except DB_PASSWORD is either generated or has a working production default.
# DB_PASSWORD cannot be generated: it has to match the password already set on the
# PostgreSQL role that the backend connects as, which lives on the host, not in git.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    -h|--help) sed -n '3,16p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $arg (try --help)" >&2; exit 2 ;;
  esac
done

if [[ -e "$ENV_FILE" && $FORCE -eq 0 ]]; then
  echo "refusing to overwrite existing $ENV_FILE" >&2
  echo "re-run with --force if you really want to regenerate it (this rotates JWT_SECRET," >&2
  echo "which logs every active session out)." >&2
  exit 1
fi

if ! command -v openssl >/dev/null 2>&1; then
  echo "openssl is required to generate secrets. Install it (apt install openssl) and retry." >&2
  exit 1
fi

# URL/shell-safe secrets: base64 with +/= stripped, so nothing needs quoting downstream
# and the seed passwords can be typed into a login form without escaping surprises.
gen_secret() { openssl rand -base64 48 | tr -d '+/=\n' | cut -c1-40; }

# DB_PASSWORD: argument-free prompt, or inherited from the environment for automation.
DB_PASSWORD="${DB_PASSWORD:-}"
if [[ -z "$DB_PASSWORD" ]]; then
  echo "PostgreSQL password for role '${DB_USERNAME:-daleel}' on this host."
  echo "(This must match the existing database — it is not generated.)"
  read -r -s -p "DB_PASSWORD: " DB_PASSWORD
  echo
fi
if [[ -z "$DB_PASSWORD" ]]; then
  echo "DB_PASSWORD cannot be empty — the backend fails at startup without it." >&2
  exit 1
fi

JWT_SECRET="$(gen_secret)"
ADMIN_PASSWORD="$(gen_secret | cut -c1-20)"
SUPERADMIN_PASSWORD="$(gen_secret | cut -c1-20)"

# Create with 600 up front so the secrets are never briefly world-readable.
umask 077
cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Never commit this file — it is gitignored on purpose.

# PostgreSQL runs on the host, not in compose; host.docker.internal resolves to the
# host gateway thanks to the extra_hosts entry in docker-compose.yml.
DB_HOST=${DB_HOST:-localhost}
DB_DOCKER_HOST=${DB_DOCKER_HOST:-host.docker.internal}
DB_PORT=${DB_PORT:-5432}
DB_NAME=${DB_NAME:-dataentry}
DB_USERNAME=${DB_USERNAME:-daleel}
DB_PASSWORD=${DB_PASSWORD}

JWT_SECRET=${JWT_SECRET}

# Browser origins allowed to call the API with credentialed cookies. Must list the real
# frontend origin — a wildcard is rejected at boot by SecurityConfig.
APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS:-https://dataentry.neurix.uk}

APP_SEED_ADMIN_USERNAME=${APP_SEED_ADMIN_USERNAME:-admin}
APP_SEED_ADMIN_PASSWORD=${ADMIN_PASSWORD}
APP_SEED_SUPERADMIN_USERNAME=${APP_SEED_SUPERADMIN_USERNAME:-superadmin}
APP_SEED_SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD}

# https deployment: leave true so the auth cookie is only sent over TLS.
APP_AUTH_COOKIE_SECURE=${APP_AUTH_COOKIE_SECURE:-true}
APP_LOGIN_RATE_STORAGE=${APP_LOGIN_RATE_STORAGE:-database}
APP_UPLOADS_PER_USER_DAILY_BYTES=${APP_UPLOADS_PER_USER_DAILY_BYTES:-524288000}

TRANSLATION_BASE_URL=${TRANSLATION_BASE_URL:-http://libretranslate:5000}
TRANSLATION_API_KEY=${TRANSLATION_API_KEY:-}
EOF
chmod 600 "$ENV_FILE"

# Printed once, here only. The seeds are applied on first boot of an empty database;
# if the users already exist their passwords are left alone and these values are unused.
cat <<EOF

Wrote $ENV_FILE (mode 600).

Seed credentials — save these now, they are not shown again:

  admin      : ${ADMIN_PASSWORD}
  superadmin : ${SUPERADMIN_PASSWORD}

These apply only when seeding a fresh database. If the users already exist, keep using
their current passwords.

Next:

  sudo docker compose up -d --build

If the backend logs show 'password authentication failed for user "${DB_USERNAME:-daleel}"',
the DB_PASSWORD above does not match the host PostgreSQL role. Fix it with:

  sudo -u postgres psql -c "ALTER ROLE ${DB_USERNAME:-daleel} WITH PASSWORD '<new-password>';"

then re-run this script with --force.
EOF
