// Scene list: id, on-screen caption (lower third) and the English voice-over text.
export const VOICE = 'en-US-AndrewMultilingualNeural';

export const SCENES = [
  { id: 'intro', caption: null,
    text: 'Meet Neurix: the data-entry platform that turns scanned books, reports and documents into clean, structured knowledge. One workspace for your agents, your team leaders, and your data pipeline.' },
  { id: 'login', caption: 'Secure sign-in · JWT authentication, brute-force protection, role-based access',
    text: 'It starts with a secure sign-in: JSON Web Token authentication, brute-force protection, and role-based access for agents, team leaders and super admins. And the whole interface speaks both English and Arabic.' },
  { id: 'ch1', caption: null, text: 'First, the people doing the work: the data-entry agents.' },
  { id: 'dash_user', caption: 'Personal dashboard · streaks, daily trend, status breakdown',
    text: 'Every agent gets a personal dashboard: today\'s submissions, weekly momentum, streaks, a thirty-day trend, and a breakdown by department and status. Everyone sees their own progress at a glance.' },
  { id: 'submit_form', caption: 'New Entry · dynamic forms with admin-defined custom fields',
    text: 'Creating an entry is fast. Pick the project, department and subcategory, and the form adapts instantly, with the custom fields your team leader defined: dropdowns, dates, numbers, links and emails.' },
  { id: 'submit_ocr', caption: 'Extract text from any file · built-in OCR, Arabic and English',
    text: 'Working from scans? Upload a PDF, Word, Excel, PowerPoint or image, and Neurix extracts the text with built-in OCR, in Arabic and English, and pulls out the embedded images too.' },
  { id: 'submit_ai', caption: 'AI content check · multi-article submit · automatic translation',
    text: 'The AI content check tidies spacing, punctuation and capitalisation before you submit. Add several articles in one go, attach documents, and send them off. Everything is translated between Arabic and English on the server, automatically.' },
  { id: 'my_entries', caption: 'My Entries · status tracking, search and attachments',
    text: 'Every submission stays within reach: search your entries, follow their status, and open the full details, including the attached documents.' },
  { id: 'folders_user', caption: 'Project Folders · streaming bulk upload with live progress',
    text: 'Project Folders make bulk work effortless. Drop dozens of scanned pages into a folder: uploads stream straight to disk, three at a time, with live progress, duplicate detection, and files up to five hundred megabytes.' },
  { id: 'notify', caption: 'Notifications · know the moment your work is approved',
    text: 'Stay in the loop with in-app notifications the moment your work is approved.' },
  { id: 'assistant', caption: 'Neurix assistant · ask a question, jump straight to the page',
    text: 'Ask the built-in Neurix assistant where anything lives, and it takes you straight there.' },
  { id: 'theme', caption: 'Dark mode · Arabic with full right-to-left layout',
    text: 'Switch to dark mode, or flip the entire interface to Arabic with full right-to-left support, in a single click.' },
  { id: 'ch2', caption: null, text: 'Next, the team leaders who run the operation.' },
  { id: 'dash_admin', caption: 'Team dashboard · KPIs, weekly progress, domain overview, leaderboard',
    text: 'Team leaders get the full picture: headcount, pending work, completions today, a weekly progress chart, top performers, and a domain overview for every department, with a live agent leaderboard.' },
  { id: 'members', caption: 'Team Members · accounts, roles, access control, bulk add',
    text: 'Manage your roster in seconds: create accounts, assign roles, deactivate access, or bulk-add a whole team, with instant feedback.' },
  { id: 'structure', caption: 'Projects · Departments · Subcategories · custom form builder',
    text: 'Structure the work your way. Projects carry timelines, progress and assigned members. Departments group them, subcategories refine them, and each subcategory gets its own custom form, with no code changes.' },
  { id: 'tasks', caption: 'Data Entry Tasks · filter, search, inline status, full review',
    text: 'Review every entry in one place. Filter by department, status or date, search across content, change status inline, and open any entry to read the full article and download its attachments.' },
  { id: 'approve', caption: 'Project Folders · one-click approvals with instant notifications',
    text: 'Approvals take one click. Open a project folder, review what your agents uploaded, approve individually or in bulk, and the agent is notified instantly.' },
  { id: 'reports', caption: 'Reports · task distribution, top performers, fill rates, agent activity',
    text: 'Reports turn activity into insight: task distribution, week-over-week comparisons, top performers and field fill rates. Drill into any agent to see daily submissions, broken down by department, subcategory and status.' },
  { id: 'ch3', caption: null, text: 'And finally, the super admins, and the data pipeline.' },
  { id: 'super', caption: 'Super Admin · isolated teams, enter any workspace, impersonation banner',
    text: 'Super admins oversee every team from one console. Each team is a fully isolated workspace with its own users, projects and entries. Enter any team to work inside its data, with a persistent banner so you never lose track, then exit with one click.' },
  { id: 'explorer', caption: 'Project analytics · Data explorer across every team',
    text: 'Cross-team project analytics show every project, its admins and its members. The data explorer searches every entry in every team, with its uploads, custom fields and submitter, ready for inspection.' },
  { id: 'pipeline', caption: 'Dataset publishing · API tokens · versioned export API for AI',
    text: 'This is where Neurix becomes a data pipeline. Publish a de-duplicated dataset snapshot, then create a read-only API token, shown exactly once, so external systems and AI projects can pull entries, documents and content hashes through the versioned export API.' },
  { id: 'platform', caption: null,
    text: 'Under the hood: Java seventeen and Spring Boot three, React eighteen with TypeScript, PostgreSQL, and self-hosted translation, all shipped as a single Docker Compose stack, with audit logging, upload quotas and per-team isolation built in.' },
  { id: 'outro', caption: null, text: 'Neurix. Manage data entry with confidence.' },
];
